"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[~~>](bold #7dcfff)'                               #   /  / _ / '➜'
error_symbol = "[x](bold #e0af68)[x](bold #ff9e64)[x](bold #f7768e)" #  /  /  
#success_symbol = '[ _ ](bold green)'
#error_symbol = "[   ](bold red)"     #  /  /  


[package]
disabled = false
style = "bold #FFFFFF"

[directory]
home_symbol = "~"
disabled = false
