"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true


[character] # The name of the module we are configuring is 'character'
success_symbol = '[ _ ](bold #86FF55)' #   /  / _ / '➜'
error_symbol = "[   ](bold #86FF55)"    #  /  /   


[package]
disabled = false
style = "bold #FFFFFF"

[directory]
home_symbol = "~"
disabled = false