format = """
$username $directory $git_branch
$character"""

add_newline = true

[username]
show_always = true
style_user = "italic fg:#ffd2b0"
format = "[$user]($style)"

[directory]
style = "fg:#bdf5cb"
format = "in [$path]($style)"
truncation_length = 3
truncation_symbol = ""

[git_branch]
symbol = "î‚  " 
style = "fg:#b6d8ff"
format = "on [$symbol$branch]($style) "

[character]
success_symbol = "[>](bold fg:#f0f6fc)"
error_symbol = "[x](bold fg:#f85149)"
