"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true


[character] # The name of the module we are configuring is 'character'
success_symbol = '[ _ ](bold #FFFFFF)' #   /  / _ / '➜'
error_symbol = "[  ](bold #e50000)"    #  /  /  


[package]
disabled = false

[directory]
home_symbol = ""
disabled = true

[[battery.display]]
threshold = 30
style = 'bold red'

[git_branch]
style = "bold #FFFFFF"
symbol = " "

[git_status]
style = "#E5E5E5"
conflicted = "="
ahead = "⇡"
diverged = "⇕"
behind = "⇣"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[git_commit]
style = "#CCCCCC"

[git_state]
style = "#DDDDDD"

