"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true









# OLD CONFIG
#[character] 
#success_symbol = '[ _ ](bold #73C2FF)' #   /  / _ / '➜'
#error_symbol = "[   ](bold #f81a1a)"    #  /  /  
#success_symbol = '[ _ ](bold green)'
#error_symbol = "[   ](bold red)"     #  /  /  


#[package]
#disabled = false
#style = "bold #FFFFFF"

#[directory]
#home_symbol = "~"
#disabled = false

