"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[OK>](bold #58d1eb)' #   /  / ](bold #7dcfff)' #   /  / ](bold #7dcfff)' #   /  / ](bold #7dcfff)' #   /  / _ / '➜'
error_symbol = "[ERR>](bold #f4005f)"  #  /  /  
#success_symbol = '[ _ ](bold green)'
#error_symbol = "[   ](bold red)"     #  /  /  


[package]
disabled = false
style = "bold #FFFFFF"

[directory]
home_symbol = "~"
disabled = false
